version: '3'
services:
  api:
    environment:
      - SESSION_SECRET
      - DB_URL
    image: 'engramapp/api'
    depends_on:
      - mongodb
    ports:
      - "3939:3939"
  auth:
    image: 'engramapp/auth'
    ports:
      - "80:80"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ./db/:/data/db